### ISSUE TITLE
The 'hx-prompt' attribute doesn't do anything after entering value

### ISSUE THREAD

**Issue by onyekaa** [bigskysoftware/htmx#478]
I've been playing around with HTMX but I can't seem to figure out how I'm supposed to get the value from `hx-prompt`. It pops up the dialog, but if you enter something and click okay, nothing happens, the modal just closes. Per the docs the value is passed to the request via a header, but no request is even triggered. The demo doesn't appear to work either: https://htmx.org/examples/dialogs/

 Am I misunderstanding how this works or is this a bug? Can confirm that `hx-confirm` actually works.

**Comment by 1cg** [comment]
Hi @onyekaa,

It should be available via the `HX-Prompt` HTTP header:

https://github.com/bigskysoftware/htmx/blob/13acf899d7a754f49c3f97d7d090c57e183575d5/src/htmx.js#L1801

Are you not seeing it as a header?

Thanks for pointing out that the demo isn't working, I will investigate.

**Comment by 1cg** [comment]
Ah, the old "no brace after the if statement" trick... :/

Fixed in dev, will go out in 1.4  Sorry about that!

**Comment by hitaloramon** [comment]
I'm trying to use the prompt, but no request is made to the server when filling in the field, not even in the browser console does anything appear. I put the dev version that mentioned that it was fixed, but it still doesn't work. Do I have to do anything else?

` <a hx-post = "/route" hx-prompt="Name." >Add</a> `
